### ISSUE TITLE
Chapter 15 - Ansible

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Mastering-Linux-Administration#2]
In the book it says to use Ubuntu Server for the neptune host, but in the `15/LAB.md` file it says to use Ubuntu Desktop. Just wondering if it matters which one we use.

**Comment by julianbalog** [comment]
It shouldn't really matter if it's Ubuntu Server or Desktop. The choice of using Ubuntu Desktop on the Ansible control node (`neptune`), as documented in `15/LAB.md`, is purely semantic, suggesting that the control node can simply be a desktop system (not a server one). For the backend web/db server nodes (`web1`, `web2`, `db1`, `db2`) we chose Ubuntu Server (and CentOS) for the same semantic reason, to illustrate "real-world" server platforms subject to automation.

We're sorry for the mismatching information between the book and the hands-on lab documents.

**Comment by ghost** [comment]
Ok, great! Thank you!
